{% set name = "gstlal-ugly" %}
{% set version = "1.11.0" %}

# dependencies
{% set framecpp_version = "2.6.2" %}
{% set gds_version = "2.19.0" %}
{% set gobject_introspection_version = "1.30.0" %}
{% set gstlal_version = "1.11.0" %}
{% set lal_version = "7.2.4" %}
{% set lalmetaio_version = "3.0.2" %}
{% set ligo_scald_version = "0.8.0" %}
{% set ligo_segments_version = "1.4.0" %}
{% set nds2_version = "0.11.5" %}
{% set python_ligo_lw_version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 4eb80e8adf6a582160ebfb422dc206643babd5446fd437a4f3507a07bfe08521

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # not linked, but needed at runtime
    - gobject-introspection
    - gst-plugins-good
    - gst-python
    - numpy
    # configure asks for it, but it is never actually used
    - liblalmetaio
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - fftw
    - gds-framexmit >={{ gds_version }}  # [linux]
    - gds-lsmp >={{ gds_version }}  # [linux]
    - glib
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gstreamer
    - gst-plugins-base
    - gst-python
    - gstlal >={{ gstlal_version }}
    - ldas-tools-al
    - ldas-tools-framecpp >={{ framecpp_version }}
    - liblal >={{ lal_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - ligo-scald >={{ ligo_scald_version }}
    - ligo-segments >={{ ligo_segments_version }}
    - nds2-client >={{ nds2_version }}
    - numpy
    - python
    - python-lal
    - python-ligo-lw >={{ python_ligo_lw_version }}
  run:
    - fftw
    - gds-framexmit >={{ gds_version }}  # [linux]
    - gds-lsmp >={{ gds_version }}  # [linux]
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gst-plugins-base
    - gst-plugins-good
    - gst-python
    - gstreamer
    - gstlal >={{ gstlal_version }}
    - h5py
    - ldas-tools-al
    - ldas-tools-framecpp >={{ framecpp_version }}
    - liblal >={{ lal_version }}
    - ligo-scald >={{ ligo_scald_version }}
    - ligo-segments >={{ ligo_segments_version }}
    - matplotlib-base
    - numpy
    - python
    - python-lal
    - python-lalsimulation
    - python-ligo-lw >={{ python_ligo_lw_version }}
    - scipy

test:
  requires:
    - python-confluent-kafka
  imports:
    - gstlal.aggregator
    - gstlal.events
    - gstlal.metric
    - gstlal.tree
  commands:
    # check gstreamer modules
    - gst-inspect-1.0 framecpp
    - gst-inspect-1.0 gds  # [linux]
    - gst-inspect-1.0 gstlalugly
    - gst-inspect-1.0 nds
    # check executables
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    - export GSTLAL_FIR_WHITEN=0
    - gstlal_condor_top --help
    - gstlal_dag_run_time --help
    - gstlal_glitch_population --help
    - gstlal_harmonic_mean_psd --help
    - gstlal_ifo_stat --help
    - gstlal_injsplitter --help
    - gstlal_kafka_dag --help
    - gstlal_ll_dq --help
    - gstlal_ligolw_add_without_reassign --help
    - gstlal_median_of_psds --help
    - gstlal_reduce_dag --help
    - gstlal_segments_operations --help
    - gstlal_segments_trim --help

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for GW data analysis (in-development parts)
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write
    such elements.  The code here sits on top of several other libraries,
    notably the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific
    Library (GSL), and, of course, GStreamer.
    This package contains the plugins and shared libraries required to run
    gstlal-based applications.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
