{% set name = "gstlal-ugly" %}
{% set version = "1.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: bec47393e63e5a052778f3b41d5cacfcd25688bbdc305ec3d1c439b85a9f2d4b
  patches:
    # https://git.ligo.org/lscsoft/gstlal/issues/43
    - gstaudio-link.patch

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win or py>30]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - fftw
    - glib
    - gobject-introspection >=1.30.0
    - gsl
    - gstreamer
    - gst-plugins-base
    - gst-python
    - gstlal >=1.6.0
    - lal >=6.19.0
    - lalmetaio >=1.5.0
    - ldas-tools-al
    - ldas-tools-framecpp >=2.6.2
    - ligo-scald >=0.7.2
    - ligo-segments >=1.2.0
    - lscsoft-glue >=2.0.0
    - metaio >=1.4.0
    - nds2-client >=0.11.5
    - numpy >=1.7.0
    - pygobject >=3.14
    - python
    - python-lal
    - python-ligo-lw >=1.5.3
  run:
    - fftw
    - gobject-introspection >=1.30.0
    - gsl
    - gst-plugins-base
    - gst-plugins-good
    - gst-python
    - gstreamer
    - gstlal >=1.6.0
    - h5py
    - lal >=6.19.2
    - lalmetaio >=1.5.0
    - lalapps >=6.23.0
    - ldas-tools-al
    - ldas-tools-framecpp >=2.6.2
    - ligo-scald >=0.7.2
    - ligo-segments >=1.2.0
    - lscsoft-glue >=2.0.0
    - matplotlib-base
    - numpy
    - pygobject >=3.14
    - python
    - python-lal
    - python-lalsimulation
    - python-ligo-lw >=1.5.3
    - scipy

test:
  imports:
    - gstlal
    - gstlal.aggregator
    - gstlal.gviz_api
    - gstlal.metric
    - gstlal.tree
  commands:
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    # check executables
    - gstlal_condor_top --help
    - gstlal_dag_run_time --help
    - gstlal_glitch_population --help
    - gstlal_harmonic_mean_psd --help
    - gstlal_kafka_dag --help
    - gstlal_ligolw_add_without_reassign --help
    - gstlal_median_of_psds --help
    - gstlal_reduce_dag --help
    - gstlal_segments_operations --help
    - gstlal_segments_trim --help

about:
  home: "https://lscsoft.docs.ligo.org/gstlal/"
  dev_url: "https://git.ligo.org/lscsoft/gstlal/"
  doc_url: "https://lscsoft.docs.ligo.org/gstlal/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "GStreamer for GW data analysis (in-development parts)"
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write
    such elements.  The code here sits on top of several other libraries,
    notably the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific
    Library (GSL), and, of course, GStreamer.
    This package contains the plugins and shared libraries required to run
    gstlal-based applications.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
