{% set name = "gstlal-ugly" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 4862d3c7324029ee2a2f3c6ad263c8cf4339f5cf7dcb9bfc4ca238593a1ae9b8

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # not linked, but needed at runtime
    - gobject-introspection
    - gst-plugins-good
    - gst-python
    # configure asks for it, but it is never actually used
    - liblalmetaio
  number: 0
  skip: true  # [win or py>36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - fftw
    - glib
    - gobject-introspection >=1.30.0
    - gsl
    - gstreamer
    - gst-plugins-base
    - gst-python
    - gstlal >=1.8.0
    - ldas-tools-al
    - ldas-tools-framecpp >=2.6.2
    - liblal >=7.1.0
    - liblalmetaio >=2.0.0
    - ligo-scald >=0.7.2
    - ligo-segments >=1.2.0
    - lscsoft-glue >=2.0.0
    - metaio >=1.4.0
    - nds2-client >=0.11.5
    - numpy
    - pygobject >=3.14
    - python
    - python-lal
    - python-ligo-lw >=1.6.0
  run:
    - fftw
    - gobject-introspection >=1.30.0
    - gsl
    - gst-plugins-base
    - gst-plugins-good
    - gst-python
    - gstreamer
    - gstlal >=1.8.0
    - h5py
    - ldas-tools-al
    - ldas-tools-framecpp >=2.6.2
    - liblal
    - ligo-scald >=0.7.2
    - ligo-segments >=1.2.0
    - lscsoft-glue >=2.0.0
    - matplotlib-base
    - numpy
    - pygobject >=3.14
    - python
    - python-lal
    - python-lalsimulation
    - python-ligo-lw >=1.6.0
    - scipy

test:
  requires:
    - python-confluent-kafka
  imports:
    - gstlal
    - gstlal.aggregator
    - gstlal.events
    - gstlal.metric
    - gstlal.tree
  commands:
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    # check executables
    - gstlal_condor_top --help
    #- gstlal_dag_run_time --help  <-- still using python2 imports
    - gstlal_glitch_population --help
    - gstlal_harmonic_mean_psd --help
    - gstlal_kafka_dag --help
    - gstlal_ligolw_add_without_reassign --help
    - gstlal_median_of_psds --help
    - gstlal_reduce_dag --help
    - gstlal_segments_operations --help
    - gstlal_segments_trim --help

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for GW data analysis (in-development parts)
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write
    such elements.  The code here sits on top of several other libraries,
    notably the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific
    Library (GSL), and, of course, GStreamer.
    This package contains the plugins and shared libraries required to run
    gstlal-based applications.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
